### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Y0geshsharma** [dhormale/google-places-autocomplete#1]
import { } from '@types/googlemaps'; gives error while compiling 
This is the issue
ERROR in src/app/add-emp/add-emp.component.ts(16,17): error TS2306: File '/home/work/test-app/node_modules/@types/googlemaps/index.d.ts' is not a module.
src/app/add-emp/add-emp.component.ts(16,17): error TS6137: Cannot import type declaration files. Consider importing 'googlemaps' instead of '@types/googlemaps'.

**Comment by nerdophile** [comment]
How did you solve it??

**Comment by Y0geshsharma** [comment]
import { MapsAPILoader } from '@agm/core';
and define const google;(at global scope )
though it throws warning but works.
it worked perfectly for me.Additionally if first build failed try hitting "enter"in between the code line and when it compiles it works.

**Comment by ramax495** [comment]
My solution is:
- add _index.d.ts_ file in root directory with line: `declare module 'googlemaps';`
- in your _tsconfig.json_ add line: `"files": [ "index.d.ts" ]`
- import in your component this way: `import { } from 'googlemaps';`
